name: Case_secret_artifact
on:
    workflow_dispatch:
jobs:
    input_output:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: echo "Input ${{ secrets.secret_file }}" >result.txt
            - uses: actions/upload-artifact@v2
              with:
                  name: result
                  path: result.txt
                  retention-days: 1
